/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StockLedger.java
 *
 * Created on Oct 16, 2012, 12:58:30 PM
 */
package misReports;

import hms.HMS101;
import hms.HMSHome;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JComponent;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import support.Library;
import support.PickList;

/**
 *
 * @author nice
 */
public class StockSummaryByBatch extends javax.swing.JInternalFrame {

    Connection dataConnection = null;
    Library lb = new Library();
    private DefaultTableModel dtm = null;
    private ResultSet viewDataRs = null;
    private PickList itemPicklist = null;

    /**
     * Creates new form StockLedger
     */
    public StockSummaryByBatch() {
        initComponents();
        initOther();
    }

    public StockSummaryByBatch(String prd_name, String fromDate, String toDate) {
        initComponents();
        initOther();
        jtxtPrdName.setText(prd_name);
        jtxtFromDate.setText(fromDate);
        jbtnView.doClick();
    }

    private void initOther() {
        this.dataConnection = HMS101.connMpAdmin;
        lb.setShortcut(this, jbtnClose);
        lb.setDateChooserPropertyInit(jtxtFromDate);
        dtm = (DefaultTableModel) jTable1.getModel();
        registerShortKeys();
        jTable1.setAutoCreateRowSorter(true);
        setPickListView();
        setPermission();
    }

    private void setPermission() {
    }

    private void setPickListView() {

        itemPicklist = new PickList(dataConnection);
        itemPicklist.setLayer(this.getLayeredPane());
        itemPicklist.setPickListComponent(jtxtPrdName);
        itemPicklist.setReturnComponent(new JTextField[]{jtxtPrdName});
        itemPicklist.setNextComponent(jbtnView);
    }

    @Override
    public void dispose() {
        try {
            HMSHome.removeFromScreen(HMSHome.tabbedPane.getSelectedIndex());
            super.dispose();
        } catch (Exception ex) {
            lb.printToLogFile("Exception at dispose at codeBinding", ex);
        }
    }

    private void registerShortKeys() {
        lb.setShortcut(this, jbtnClose);

        KeyStroke dateKeyStroke = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0, false);
        Action dateKeyAction = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jtxtFromDate.requestFocusInWindow();
            }
        };
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(dateKeyStroke, "Date");
        getRootPane().getActionMap().put("Date", dateKeyAction);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jtxtPrdName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jbtnView = new javax.swing.JButton();
        jbtnClose = new javax.swing.JButton();
        jtxtFromDate = new com.toedter.calendar.JDateChooser();
        jCheckBox1 = new javax.swing.JCheckBox();

        setClosable(true);
        setIconifiable(true);
        setTitle("Stock Ledger");

        jPanel1.setLayout(new java.awt.CardLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "batch No", "MFG", "EXP", "Qty"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(80);
        }

        jPanel1.add(jScrollPane1, "card2");

        jLabel2.setText("Product Name");

        jtxtPrdName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtPrdNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtPrdNameFocusLost(evt);
            }
        });
        jtxtPrdName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtPrdNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtPrdNameKeyReleased(evt);
            }
        });

        jLabel3.setText("Exp Date Near");

        jbtnView.setText("View Result");
        jbtnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnViewActionPerformed(evt);
            }
        });
        jbtnView.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnViewKeyPressed(evt);
            }
        });

        jbtnClose.setText("Close");
        jbtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCloseActionPerformed(evt);
            }
        });

        jtxtFromDate.setEnabled(false);

        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBox1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtFromDate, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtxtPrdName, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 221, Short.MAX_VALUE)
                                .addComponent(jbtnView, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbtnClose, jbtnView});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtnView)
                        .addComponent(jbtnClose))
                    .addComponent(jtxtPrdName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jCheckBox1))
                    .addComponent(jtxtFromDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, jtxtPrdName});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel3, jtxtFromDate});

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jtxtPrdNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtPrdNameFocusGained
// TODO add your handling code here:
    jtxtPrdName.selectAll();
}//GEN-LAST:event_jtxtPrdNameFocusGained

private void jtxtPrdNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPrdNameKeyPressed
    itemPicklist.setLocation(jtxtPrdName.getX(), jtxtPrdName.getY());
    itemPicklist.pickListKeyPress(evt);
}//GEN-LAST:event_jtxtPrdNameKeyPressed

private void jtxtPrdNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPrdNameKeyReleased
    try {
        String sql = "SELECT bill_item_name FROM billitemmst"
                + " WHERE bill_item_name LIKE '%" + jtxtPrdName.getText().toUpperCase() + "%'"
                + " and bill_grp_cd=8";
        PreparedStatement pstLocal = dataConnection.prepareStatement(sql);
        itemPicklist.setPreparedStatement(pstLocal);
        itemPicklist.setValidation(dataConnection.prepareStatement("SELECT bill_item_name FROM billitemmst WHERE bill_item_name =? "
                + "and bill_grp_cd=8"));
        itemPicklist.pickListKeyRelease(evt);
    } catch (Exception ex) {
        lb.printToLogFile("Exception at jtxtProductKeyReleased in Stock Ledger", ex);
    }
}//GEN-LAST:event_jtxtPrdNameKeyReleased

private void jbtnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnViewActionPerformed
// TODO add your handling code here:
    javax.swing.SwingUtilities.invokeLater(new Runnable() {
        public void run() {
            if (true) {
                jbtnViewResultActionPerformedRoutine();
                lb.setColumnSizeForTable(jTable1, jPanel1.getWidth());
            }
        }
    });
}//GEN-LAST:event_jbtnViewActionPerformed

private void jbtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCloseActionPerformed
// TODO add your handling code here:
    this.dispose();
}//GEN-LAST:event_jbtnCloseActionPerformed

private void jbtnViewKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnViewKeyPressed
// TODO add your handling code here:
    lb.enterClick(evt);

}//GEN-LAST:event_jbtnViewKeyPressed

private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
// TODO add your handling code here:
    final java.awt.event.MouseEvent tempEvt = evt;
    SwingUtilities.invokeLater(new Runnable() {

        public void run() {

            Thread threadForjbtntableViewMouseClicked = new Thread() {

                public void run() {
                    tableViewOnPanel1MouseClickedRoutine(tempEvt);
                }

            };
            threadForjbtntableViewMouseClicked.start();

        }
    });
}//GEN-LAST:event_jTable1MouseClicked

    private void jtxtPrdNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtPrdNameFocusLost
        itemPicklist.setVisible(false);
    }//GEN-LAST:event_jtxtPrdNameFocusLost

    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1ItemStateChanged
        // TODO add your handling code here:
        jtxtFromDate.setEnabled(jCheckBox1.isSelected());
    }//GEN-LAST:event_jCheckBox1ItemStateChanged

    private void tableViewOnPanel1MouseClickedRoutine(java.awt.event.MouseEvent evt) {
        if (evt.getClickCount() == 2) {
//            lb.displayQuickForm(jTable1.getValueAt(jTable1.getSelectedRow(), jTable1.getColumnCount()-1).toString());
        }
    }

    private void makeQuery() throws SQLException {
        String sql = "SELECT b.bill_item_name,m.batch_no,DATE_FORMAT(m.mfg_date, '%d/%m/%Y') AS mfg_date ,\n"
                + " DATE_FORMAT(m.exp_date, '%d/%m/%Y') AS exp_date,(SELECT SUM(CASE WHEN DOC_CD='PUR' THEN QTY ELSE QTY*-1 END) AS opb FROM OLDB0_3\n"
                + " WHERE bill_item_cd=m.bill_item_cd AND batch_no=m.batch_no) AS qty FROM medstk m \n"
                + " LEFT JOIN billitemmst b ON m.bill_item_cd=b.bill_item_cd \n"
                + " WHERE 0 < (SELECT SUM(CASE WHEN DOC_CD='PUR' THEN QTY ELSE QTY*-1 END) AS opb FROM OLDB0_3\n"
                + " WHERE bill_item_cd=m.bill_item_cd) ";
        if (!jtxtPrdName.getText().isEmpty()) {
            sql += " and m.bill_item_cd=" + lb.getbillitemCode(jtxtPrdName.getText(), "C");
        }

        if (jCheckBox1.isSelected()) {
            sql += " and m.exp_date<='" + lb.ConvertDateFormetForDB(jtxtFromDate.getText()) + "'";
        }
        sql += " ORDER BY m.exp_date";
        PreparedStatement pstLocal = dataConnection.prepareStatement(sql);
        viewDataRs = pstLocal.executeQuery();

    }

    private void jbtnViewResultActionPerformedRoutine() {
        try {
            makeQuery();
            dtm.setRowCount(0);
            while (viewDataRs.next()) {
                Vector row = new Vector();
                row.add(viewDataRs.getString("bill_item_name"));
                row.add(viewDataRs.getString("batch_no"));
                row.add(viewDataRs.getString("mfg_date"));
                row.add(viewDataRs.getString("exp_date"));
                row.add(viewDataRs.getString("qty"));
                dtm.addRow(row);
            }
        } catch (Exception ex) {
            lb.printToLogFile("Exception at view Result in stock ledger", ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnClose;
    private javax.swing.JButton jbtnView;
    private com.toedter.calendar.JDateChooser jtxtFromDate;
    private javax.swing.JTextField jtxtPrdName;
    // End of variables declaration//GEN-END:variables
}
