/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StockLedger.java
 *
 * Created on Oct 16, 2012, 12:58:30 PM
 */
package misReports;

import hms.HMS101;
import hms.HMSHome;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JComponent;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import support.Library;
import support.PickList;

/**
 *
 * @author nice
 */
public class StockLedger extends javax.swing.JInternalFrame {

    Connection dataConnection = null;
    Library lb = new Library();
    private DefaultTableModel dtm = null;
    private ResultSet viewDataRs = null;
    private PickList itemPicklist = null;

    /**
     * Creates new form StockLedger
     */
    public StockLedger() {
        initComponents();
        initOther();
    }

    public StockLedger(String prd_name, String fromDate, String toDate) {
        initComponents();
        initOther();
        jtxtPrdName.setText(prd_name);
        jtxtFromDate.setText(fromDate);
        jtxtToDate.setText(toDate);
        jbtnView.doClick();
    }

    private void initOther() {
        this.dataConnection = HMS101.connMpAdmin;
        lb.setShortcut(this, jbtnClose);
        lb.setDateChooserPropertyInit(jtxtToDate);
        lb.setDateChooserPropertyInit(jtxtFromDate);
        dtm = (DefaultTableModel) jTable1.getModel();
        jtxtPrdName.setText("Enter productName");
        registerShortKeys();
        jTable1.setAutoCreateRowSorter(true);
        setTextfieldsAtBottom();
        setPickListView();
        setPermission();
    }

    private void setPermission() {
    }

    private void setPickListView() {

        itemPicklist = new PickList(dataConnection);
        itemPicklist.setLayer(this.getLayeredPane());
        itemPicklist.setPickListComponent(jtxtPrdName);
        itemPicklist.setReturnComponent(new JTextField[]{jtxtPrdName});
        itemPicklist.setNextComponent(jbtnView);
    }

    @Override
    public void dispose() {
        try {
            HMSHome.removeFromScreen(HMSHome.tabbedPane.getSelectedIndex());
            super.dispose();
        } catch (Exception ex) {
            lb.printToLogFile("Exception at dispose at codeBinding", ex);
        }
    }

    private void registerShortKeys() {
        lb.setShortcut(this, jbtnClose);

        KeyStroke dateKeyStroke = KeyStroke.getKeyStroke(KeyEvent.VK_D, KeyEvent.ALT_MASK, false);
        Action dateKeyAction = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jtxtFromDate.requestFocusInWindow();
            }
        };
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(dateKeyStroke, "Date");
        getRootPane().getActionMap().put("Date", dateKeyAction);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jlbClosingBal = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtPrdName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jbtnView = new javax.swing.JButton();
        jbtnClose = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jlblOpb = new javax.swing.JLabel();
        jtxtFromDate = new com.toedter.calendar.JDateChooser();
        jtxtToDate = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        setIconifiable(true);
        setTitle("Stock Ledger");

        jPanel1.setLayout(new java.awt.CardLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Voucher No", "Book", "Issue", "Reciept", "Balance", "Ref"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(6).setMinWidth(0);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(0);
            jTable1.getColumnModel().getColumn(6).setMaxWidth(0);
        }

        jPanel1.add(jScrollPane1, "card2");

        jLabel1.setText("Closing Stock");

        jlbClosingBal.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlbClosingBal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbClosingBal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Product Name");

        jtxtPrdName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtPrdNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtPrdNameFocusLost(evt);
            }
        });
        jtxtPrdName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtPrdNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtPrdNameKeyReleased(evt);
            }
        });

        jLabel3.setText("From Date");

        jLabel4.setText("To Date");

        jbtnView.setText("View Result");
        jbtnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnViewActionPerformed(evt);
            }
        });
        jbtnView.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnViewKeyPressed(evt);
            }
        });

        jbtnClose.setText("Close");
        jbtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCloseActionPerformed(evt);
            }
        });

        jLabel5.setText("OPB");

        jlblOpb.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jlblOpb.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblOpb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtxtPrdName, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                                .addComponent(jbtnView, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtxtFromDate, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtToDate, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlbClosingBal, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlblOpb, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbtnClose, jbtnView});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtnView)
                        .addComponent(jbtnClose))
                    .addComponent(jtxtPrdName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jtxtFromDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxtToDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(jlblOpb, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbClosingBal, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, jtxtPrdName});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel3, jLabel4, jtxtFromDate, jtxtToDate});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel5, jlblOpb});

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jtxtPrdNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtPrdNameFocusGained
// TODO add your handling code here:
    jtxtPrdName.selectAll();
}//GEN-LAST:event_jtxtPrdNameFocusGained

private void jtxtPrdNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPrdNameKeyPressed
    itemPicklist.setLocation(jtxtPrdName.getX(), jtxtPrdName.getY());
    itemPicklist.pickListKeyPress(evt);
}//GEN-LAST:event_jtxtPrdNameKeyPressed

private void jtxtPrdNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPrdNameKeyReleased
    try {
        String sql = "SELECT bill_item_name FROM billitemmst"
                + " WHERE bill_item_name LIKE '%" + jtxtPrdName.getText().toUpperCase() + "%'"
                + " and bill_grp_cd=8";
        PreparedStatement pstLocal = dataConnection.prepareStatement(sql);
        itemPicklist.setPreparedStatement(pstLocal);
        itemPicklist.setValidation(dataConnection.prepareStatement("SELECT bill_item_name FROM billitemmst WHERE bill_item_name =? "
                + "and bill_grp_cd=8"));
        itemPicklist.pickListKeyRelease(evt);
    } catch (Exception ex) {
        lb.printToLogFile("Exception at jtxtProductKeyReleased in Stock Ledger", ex);
    }
}//GEN-LAST:event_jtxtPrdNameKeyReleased

private void jbtnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnViewActionPerformed
// TODO add your handling code here:
    javax.swing.SwingUtilities.invokeLater(new Runnable() {
        public void run() {
            if (true) {
                jbtnViewResultActionPerformedRoutine();
                lb.setColumnSizeForTable(jTable1, jPanel1.getWidth());
            }
        }
    });
}//GEN-LAST:event_jbtnViewActionPerformed

private void jbtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCloseActionPerformed
// TODO add your handling code here:
    this.dispose();
}//GEN-LAST:event_jbtnCloseActionPerformed

private void jbtnViewKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnViewKeyPressed
// TODO add your handling code here:
    lb.enterClick(evt);

}//GEN-LAST:event_jbtnViewKeyPressed

private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
// TODO add your handling code here:
    final java.awt.event.MouseEvent tempEvt = evt;
    SwingUtilities.invokeLater(new Runnable() {

        public void run() {

            Thread threadForjbtntableViewMouseClicked = new Thread() {

                public void run() {
                    tableViewOnPanel1MouseClickedRoutine(tempEvt);
                }

            };
            threadForjbtntableViewMouseClicked.start();

        }
    });
}//GEN-LAST:event_jTable1MouseClicked

    private void jtxtPrdNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtPrdNameFocusLost
        itemPicklist.setVisible(false);
    }//GEN-LAST:event_jtxtPrdNameFocusLost

    private void tableViewOnPanel1MouseClickedRoutine(java.awt.event.MouseEvent evt) {
        if (evt.getClickCount() == 2) {
//            lb.displayQuickForm(jTable1.getValueAt(jTable1.getSelectedRow(), jTable1.getColumnCount()-1).toString());
        }
    }

    private void makeQuery() throws SQLException {
        String sql = "SELECT ref_no,DOC_CD,v_date, CASE WHEN doc_cd='SAL' THEN QTY ELSE 0 END AS issue,\n"
                + "CASE WHEN DOC_CD='PUR' THEN QTY ELSE 0 END AS receipt,  \n"
                + "(SELECT SUM(CASE WHEN DOC_CD='SAL' THEN QTY*-1 ELSE QTY END) FROM OLDB0_3\n"
                + "  WHERE bill_item_cd=? AND v_date <? ) AS opb  FROM OLDB0_3 o \n"
                + "  WHERE v_date >=? AND v_date <=? AND bill_item_cd=?";
        PreparedStatement pstLocal = dataConnection.prepareStatement(sql);

        pstLocal.setString(1, lb.getbillitemCode(jtxtPrdName.getText(), "C"));
        pstLocal.setString(2, lb.ConvertDateFormetForDB(jtxtFromDate.getText()));
        pstLocal.setString(3, lb.ConvertDateFormetForDB(jtxtFromDate.getText()));
        pstLocal.setString(4, lb.ConvertDateFormetForDB(jtxtToDate.getText()));
        pstLocal.setString(5, lb.getbillitemCode(jtxtPrdName.getText(), "C"));
        viewDataRs = pstLocal.executeQuery();

    }

    private void jbtnViewResultActionPerformedRoutine() {
        try {
            int tot = 0;
            makeQuery();
            dtm.setRowCount(0);
            if (viewDataRs.next()) {
                jlblOpb.setText(viewDataRs.getString("opb"));
                tot = viewDataRs.getInt("OPB");
                Vector row = new Vector();
                row.add(lb.ConvertDateFormetForDisply(viewDataRs.getString("v_date")));
                row.add(viewDataRs.getString("ref_no"));
                row.add(viewDataRs.getString("doc_cd"));
                row.add(viewDataRs.getString("issue"));
                row.add(viewDataRs.getString("receipt"));
                tot += viewDataRs.getInt("receipt");
                tot -= viewDataRs.getInt("issue");
                row.add(tot);
                dtm.addRow(row);
                while (viewDataRs.next()) {
                    row = new Vector();
                    row.add(lb.ConvertDateFormetForDisply(viewDataRs.getString("v_date")));
                    row.add(viewDataRs.getString("ref_no"));
                    row.add(viewDataRs.getString("doc_cd"));
                    row.add(viewDataRs.getString("issue"));
                    row.add(viewDataRs.getString("receipt"));
                    tot += viewDataRs.getInt("receipt");
                    tot -= viewDataRs.getInt("issue");
                    row.add(tot);
                    dtm.addRow(row);
                }
            } else {
                jlblOpb.setText((int) lb.getOpeningStock(lb.getbillitemCode(jtxtPrdName.getText(), "C"), "QTY", jtxtFromDate.getText()) + "");
                tot = (int) lb.getOpeningStock(lb.getbillitemCode(jtxtPrdName.getText(), "C"), "QTY", jtxtFromDate.getText());
            }
            jlbClosingBal.setText(tot + "");
        } catch (Exception ex) {
            lb.printToLogFile("Exception at view Result in stock ledger", ex);
        }
    }

    private void setTextfieldsAtBottom() {
        int x = jPanel1.getX();
        int y = jPanel1.getY() + jPanel1.getHeight();
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        int sizeX[] = new int[dtm.getColumnCount()];
        for (int i = 0; i < dtm.getColumnCount(); i++) {
            sizeX[i] = jTable1.getColumn(jTable1.getColumnName(i).toString()).getWidth();
        }
        x += sizeX[0] + sizeX[1] + sizeX[2];
        jlbClosingBal.setBounds(x += sizeX[3] + sizeX[4], y, sizeX[5], 20);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnClose;
    private javax.swing.JButton jbtnView;
    private javax.swing.JLabel jlbClosingBal;
    private javax.swing.JLabel jlblOpb;
    private com.toedter.calendar.JDateChooser jtxtFromDate;
    private javax.swing.JTextField jtxtPrdName;
    private com.toedter.calendar.JDateChooser jtxtToDate;
    // End of variables declaration//GEN-END:variables
}
