/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transaction;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JDialog;
import javax.swing.table.DefaultTableModel;
import support.Library;

/**
 *
 * @author Bhaumik
 */
public class IndorPatientList extends javax.swing.JInternalFrame {

    Library lb = new Library();
    Connection dataConnection = hms.HMS101.connMpAdmin;
    DefaultTableModel dtm = null;
    JDialog jd = null;
    String opd_no = "";
    PatientMaster pm = null;

    /**
     * Creates new form SearchPatient
     */
    public IndorPatientList(JDialog jd, PatientMaster pm) {
        initComponents();
        this.pm = pm;
        this.jd = jd;
        dtm = (DefaultTableModel) jTable2.getModel();
        updateIPDList();
    }

    private void updateIPDList() {
        try {
            String sql = "";
            sql = "SELECT i.ipd_no,i.opd_no,ward_name,r.room_cd,p.pt_name FROM ipdreg i LEFT JOIN roommst r ON i.opd_no=r.opd_no "
                    + " LEFT JOIN wardmst w ON r.ward_cd=w.ward_cd LEFT JOIN patientmst p ON i.opd_no=p.opd_no WHERE is_close = 0";

            PreparedStatement pstLocal = dataConnection.prepareStatement(sql);
            ResultSet rsLcoal = pstLocal.executeQuery();
            int i = 1;
            dtm.setRowCount(0);
            while (rsLcoal.next()) {
                Vector row = new Vector();
                row.add(i);
                row.add(rsLcoal.getString("ipd_no"));
                row.add(rsLcoal.getString("opd_no"));
                row.add(rsLcoal.getString("pt_name"));
                row.add(rsLcoal.getString("ward_name"));
                row.add(rsLcoal.getString("room_cd"));
                dtm.addRow(row);
                i++;
            }
            lb.setColumnSizeForTable(jTable2, jPanel2.getWidth());
        } catch (Exception ex) {
            lb.printToLogFile("Exception at setData in appointment Book", ex);
        }
    }

    @Override
    public void dispose() {
        jd.dispose();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jPanel2.setLayout(new java.awt.BorderLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sr No", "IPD No", "OPD No", "Name", "Ward", "Bed No"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 815, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 2){
            int row = jTable2.getSelectedRow();
            if (row != -1) {
                opd_no = jTable2.getValueAt(row, 2).toString();
//                pm.jlblRefOPDNo.setText(opd_no);
                this.dispose();
            }
        }
    }//GEN-LAST:event_jTable2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
