/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package transaction;

import hms.HMS101;
import java.sql.Connection;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JTextField;
import support.Library;

/**
 *
 * @author nice
 */
public class PaymentDialog extends javax.swing.JDialog {

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;
    private Library lb = new Library();
    private JComponent focusComp = null, returnComp = null;
    private int type = -1;
    Connection dataConnection = HMS101.connMpAdmin;

    /**
     * Creates new form PaymentDialog
     */
    public PaymentDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setTitle("Payment Information");
        initComponents();
        lb.setDateChooserPropertyInit(jtxtChequeDate);

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
//        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
//        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
//        ActionMap actionMap = getRootPane().getActionMap();
//        actionMap.put(cancelName, new AbstractAction() {
//            public void actionPerformed(ActionEvent e) {
//                doClose(RET_CANCEL);
//            }
//        });
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        this.setBounds(screenSize.width / 2 - this.getWidth() / 2, screenSize.height / 2 - this.getHeight() / 2, this.getWidth(), this.getHeight());
        setCompEnable();
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    public void setFocusComp(JComponent comp) {
        focusComp = comp;
    }

    public void setReturnComp(JComponent comp) {
        returnComp = comp;
    }

    public void setInitialAmt(int type) {
        this.type = type;
        jtxtCashAmt.setText(jlblSale.getText());
        jcbCash.setSelected(true);
    }

    public void setInitialAmtForCredit() {

        jtxtCashAmt.setText(jlblSale.getText());
        jcbCash.setSelected(true);
    }

    public void setTotal() {

        double total = 0;
        if (jcbCash.isSelected()) {
            total += lb.isNumber(jtxtCashAmt);
        }
        if (jcbBank.isSelected()) {
            total += lb.isNumber(jtxtChequeAmt);
        }
        if (jcbCard.isSelected()) {
            total += lb.isNumber(jtxtCardAmt);
        }
        jlblSalePay.setText(lb.Convert2DecFmtForRs(total));
        jlblRemainPay.setText(lb.Convert2DecFmtForRs(lb.isNumber(jlblSale) - total));
    }

    private void setCompEnable() {
        jtxtCashAmt.setEnabled(jcbCash.isSelected());
        jtxtBankName.setEnabled(jcbBank.isSelected());
        jtxtBranchName.setEnabled(jcbBank.isSelected());
        jtxtChequeNo.setEnabled(jcbBank.isSelected());
        jtxtChequeDate.setEnabled(jcbBank.isSelected());
        jtxtChequeAmt.setEnabled(jcbBank.isSelected());
        jtxtCardAmt.setEnabled(jcbCard.isSelected());
        jtxtCardNo.setEnabled(jcbCard.isSelected());
    }

    public void reset() {
        jcbCash.setSelected(false);
        jcbBank.setSelected(false);
        jcbCard.setSelected(false);

        jtxtCashAmt.setText("");
        jtxtBankName.setText("");
        jtxtBranchName.setText("");
        jtxtChequeNo.setText("");
        jtxtChequeDate.setText("");
        jtxtChequeAmt.setText("");
        jtxtCardAmt.setText("");
        setCompEnable();
    }

    private boolean fieldValidate(JComponent comp) {
        boolean flag = true;
        if (comp == jlblRemainPay) {
            if (lb.isNumber(jlblRemainPay) != 0) {
                return false;
            }
        }
        return flag;
    }

    private boolean validateData() {
        boolean flag = true;
        flag = flag && fieldValidate(jlblRemainPay);
        return flag;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jcbCash = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jtxtCashAmt = new javax.swing.JTextField();
        jcbBank = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jtxtBankName = new javax.swing.JTextField();
        jtxtBranchName = new javax.swing.JTextField();
        jtxtChequeNo = new javax.swing.JTextField();
        jtxtChequeDate = new javax.swing.JTextField();
        jtxtChequeAmt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcbCard = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jtxtCardAmt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jlblSale = new javax.swing.JLabel();
        jbtnReset = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jlblSalePay = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jlblRemainPay = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtxtCardNo = new javax.swing.JTextField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        okButton.setMnemonic('O');
        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        okButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                okButtonKeyPressed(evt);
            }
        });

        cancelButton.setMnemonic('C');
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jcbCash.setText("Cash Information");
        jcbCash.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbCashItemStateChanged(evt);
            }
        });
        jcbCash.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcbCashKeyPressed(evt);
            }
        });

        jLabel1.setText("Cash Amount");

        jtxtCashAmt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtCashAmtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtCashAmtFocusLost(evt);
            }
        });
        jtxtCashAmt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtCashAmtKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtCashAmtKeyTyped(evt);
            }
        });

        jcbBank.setText("Bank Information");
        jcbBank.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbBankItemStateChanged(evt);
            }
        });
        jcbBank.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcbBankKeyPressed(evt);
            }
        });

        jLabel2.setText("Bank Name");

        jtxtBankName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtBankNameFocusGained(evt);
            }
        });
        jtxtBankName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtBankNameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtBankNameKeyTyped(evt);
            }
        });

        jtxtBranchName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtBranchNameFocusGained(evt);
            }
        });
        jtxtBranchName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtBranchNameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtBranchNameKeyTyped(evt);
            }
        });

        jtxtChequeNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtChequeNoFocusGained(evt);
            }
        });
        jtxtChequeNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtChequeNoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtChequeNoKeyTyped(evt);
            }
        });

        jtxtChequeDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtChequeDateFocusGained(evt);
            }
        });
        jtxtChequeDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtChequeDateKeyPressed(evt);
            }
        });

        jtxtChequeAmt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtChequeAmtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtChequeAmtFocusLost(evt);
            }
        });
        jtxtChequeAmt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtChequeAmtKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtChequeAmtKeyTyped(evt);
            }
        });

        jLabel6.setText("Cheque Amount");

        jLabel5.setText("Cheque Date.");

        jLabel4.setText("Cheque No.");

        jLabel3.setText("Bank Branch");

        jcbCard.setText("Credit Card Information");
        jcbCard.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbCardItemStateChanged(evt);
            }
        });
        jcbCard.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcbCardKeyPressed(evt);
            }
        });

        jLabel7.setText("Card Amount");

        jtxtCardAmt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtCardAmtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtCardAmtFocusLost(evt);
            }
        });
        jtxtCardAmt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtCardAmtKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtCardAmtKeyTyped(evt);
            }
        });

        jLabel10.setText("Total Sale Amount");

        jlblSale.setText("0.00");

        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });

        jLabel11.setText("Total Sale Pay");

        jlblSalePay.setText("0.00");

        jLabel12.setText("Remain Pay Amount");

        jlblRemainPay.setText("0.00");

        jLabel8.setText("Card Number");

        jtxtCardNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtCardNoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtCardNoFocusLost(evt);
            }
        });
        jtxtCardNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtCardNoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtCardNoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 237, Short.MAX_VALUE)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtBankName)
                            .addComponent(jtxtBranchName)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtChequeAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtChequeDate, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtChequeNo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 170, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbCash, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblSale, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlblSalePay, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlblRemainPay, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtCardAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtCashAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jcbBank)
                            .addComponent(jcbCard))
                        .addGap(0, 183, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtCardNo)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, okButton});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jLabel5, jLabel6});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jlblSale)
                    .addComponent(jbtnReset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcbCash)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtCashAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(12, 12, 12)
                .addComponent(jcbBank)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtBankName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtBranchName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtChequeNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtChequeDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtChequeAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcbCard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jtxtCardAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jtxtCardNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jlblSalePay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jlblRemainPay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel7, jLabel8, jtxtCardAmt, jtxtCardNo});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        if (validateData()) {
            doClose(RET_OK);
        }
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void jcbCashItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbCashItemStateChanged
        setCompEnable();
    }//GEN-LAST:event_jcbCashItemStateChanged

    private void jcbBankItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbBankItemStateChanged
        setCompEnable();
    }//GEN-LAST:event_jcbBankItemStateChanged

    private void jcbCardItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbCardItemStateChanged
        setCompEnable();
    }//GEN-LAST:event_jcbCardItemStateChanged

    private void jtxtBankNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBankNameKeyPressed
        lb.enterFocus(evt, jtxtBranchName);
    }//GEN-LAST:event_jtxtBankNameKeyPressed

    private void jtxtBranchNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBranchNameKeyPressed
        lb.enterFocus(evt, jtxtChequeNo);
    }//GEN-LAST:event_jtxtBranchNameKeyPressed

    private void jtxtChequeNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtChequeNoKeyPressed
        lb.enterFocus(evt, jtxtChequeDate);
    }//GEN-LAST:event_jtxtChequeNoKeyPressed

    private void jtxtChequeDateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtChequeDateKeyPressed
        lb.enterFocus(evt, jtxtChequeAmt);
    }//GEN-LAST:event_jtxtChequeDateKeyPressed

    private void jtxtCashAmtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCashAmtKeyTyped
        lb.onlyNumber(evt, jtxtCashAmt.getText().length() + 1);
    }//GEN-LAST:event_jtxtCashAmtKeyTyped

    private void jtxtChequeNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtChequeNoKeyTyped
        lb.onlyNumber(evt, jtxtChequeNo.getText().length() + 1);
    }//GEN-LAST:event_jtxtChequeNoKeyTyped

    private void jtxtChequeAmtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtChequeAmtKeyTyped
        lb.onlyNumber(evt, jtxtChequeAmt.getText().length() + 1);
    }//GEN-LAST:event_jtxtChequeAmtKeyTyped

    private void jtxtCardAmtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCardAmtKeyTyped
        lb.onlyNumber(evt, jtxtCardAmt.getText().length() + 1);
    }//GEN-LAST:event_jtxtCardAmtKeyTyped

    private void jtxtBankNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBankNameKeyTyped
        lb.fixLength(evt, 100);
    }//GEN-LAST:event_jtxtBankNameKeyTyped

    private void jtxtBranchNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBranchNameKeyTyped
        lb.fixLength(evt, 100);
    }//GEN-LAST:event_jtxtBranchNameKeyTyped

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        reset();
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jtxtCashAmtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtCashAmtFocusLost
        setTotal();
    }//GEN-LAST:event_jtxtCashAmtFocusLost

    private void jtxtChequeAmtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtChequeAmtFocusLost
        setTotal();
    }//GEN-LAST:event_jtxtChequeAmtFocusLost

    private void jtxtCardAmtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtCardAmtFocusLost
        setTotal();
    }//GEN-LAST:event_jtxtCardAmtFocusLost

    private void jtxtCashAmtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtCashAmtFocusGained
        lb.selectAll(evt);
    }//GEN-LAST:event_jtxtCashAmtFocusGained

    private void jtxtBankNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtBankNameFocusGained
        lb.selectAll(evt);
    }//GEN-LAST:event_jtxtBankNameFocusGained

    private void jtxtBranchNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtBranchNameFocusGained
        lb.selectAll(evt);
    }//GEN-LAST:event_jtxtBranchNameFocusGained

    private void jtxtChequeNoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtChequeNoFocusGained
        lb.selectAll(evt);
    }//GEN-LAST:event_jtxtChequeNoFocusGained

    private void jtxtChequeDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtChequeDateFocusGained
        lb.selectAll(evt);
    }//GEN-LAST:event_jtxtChequeDateFocusGained

    private void jtxtChequeAmtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtChequeAmtFocusGained
        lb.selectAll(evt);
    }//GEN-LAST:event_jtxtChequeAmtFocusGained

    private void jtxtCardAmtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtCardAmtFocusGained
        lb.selectAll(evt);
    }//GEN-LAST:event_jtxtCardAmtFocusGained

    private void okButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_okButtonKeyPressed
        lb.enterClick(evt);
    }//GEN-LAST:event_okButtonKeyPressed

    private void jtxtCashAmtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCashAmtKeyPressed
        lb.enterFocus(evt, jcbBank);
    }//GEN-LAST:event_jtxtCashAmtKeyPressed

    private void jtxtChequeAmtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtChequeAmtKeyPressed
        lb.enterFocus(evt, jcbCard);
    }//GEN-LAST:event_jtxtChequeAmtKeyPressed

    private void jtxtCardAmtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCardAmtKeyPressed
        lb.enterFocus(evt, jtxtCardNo);
    }//GEN-LAST:event_jtxtCardAmtKeyPressed

    private void jcbCashKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbCashKeyPressed
        // TODO add your handling code here:
        if (lb.isEnter(evt)) {
            jcbBank.requestFocusInWindow();
        }
    }//GEN-LAST:event_jcbCashKeyPressed

    private void jcbBankKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbBankKeyPressed
        // TODO add your handling code here:
        if (lb.isEnter(evt)) {
            jcbCard.requestFocusInWindow();
        }
    }//GEN-LAST:event_jcbBankKeyPressed

    private void jcbCardKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbCardKeyPressed
        // TODO add your handling code here:
        if (lb.isEnter(evt)) {
            okButton.requestFocusInWindow();
        }
    }//GEN-LAST:event_jcbCardKeyPressed

    private void jtxtCardNoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtCardNoFocusGained
        // TODO add your handling code here:
        lb.selectAll(evt);
    }//GEN-LAST:event_jtxtCardNoFocusGained

    private void jtxtCardNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtCardNoFocusLost
        // TODO add your handling code here:
        lb.toUpper(evt);
    }//GEN-LAST:event_jtxtCardNoFocusLost

    private void jtxtCardNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCardNoKeyPressed
        // TODO add your handling code here:
        lb.enterFocus(evt, okButton);
    }//GEN-LAST:event_jtxtCardNoKeyPressed

    private void jtxtCardNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCardNoKeyTyped
        // TODO add your handling code here:
        lb.onlyInteger(evt, 16);
    }//GEN-LAST:event_jtxtCardNoKeyTyped

    private void doClose(int retStatus) {
        if (retStatus == RET_OK) {
            switch (type) {
                case 0:
                    if (returnComp instanceof JTextField) {
                        ((JTextField) returnComp).setText(jlblSale.getText());
                    } else if (returnComp instanceof JLabel) {
                        ((JLabel) returnComp).setText(jlblSale.getText());
                    }
                    break;
                case 1:
                    if (returnComp instanceof JTextField) {
                        ((JTextField) returnComp).setText(jlblSalePay.getText());
                    } else if (returnComp instanceof JLabel) {
                        ((JLabel) returnComp).setText(jlblSalePay.getText());
                    }
                    break;
                case 2:
                    if (returnComp instanceof JTextField) {
                        ((JTextField) returnComp).setText(jlblSale.getText());
                    } else if (returnComp instanceof JLabel) {
                        ((JLabel) returnComp).setText(jlblSale.getText());
                    }
                    break;

            }
        } else {

        }
        returnStatus = retStatus;
        setVisible(false);
        focusComp.requestFocusInWindow();
//        dispose();
    }

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton jbtnReset;
    public javax.swing.JCheckBox jcbBank;
    public javax.swing.JCheckBox jcbCard;
    public javax.swing.JCheckBox jcbCash;
    public javax.swing.JLabel jlblRemainPay;
    public javax.swing.JLabel jlblSale;
    public javax.swing.JLabel jlblSalePay;
    public javax.swing.JTextField jtxtBankName;
    public javax.swing.JTextField jtxtBranchName;
    public javax.swing.JTextField jtxtCardAmt;
    public javax.swing.JTextField jtxtCardNo;
    public javax.swing.JTextField jtxtCashAmt;
    public javax.swing.JTextField jtxtChequeAmt;
    public javax.swing.JTextField jtxtChequeDate;
    public javax.swing.JTextField jtxtChequeNo;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
    private int returnStatus = RET_CANCEL;
}
