/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utility;

import hms.HMS101;
import hms.HMSHome;
import java.awt.event.KeyEvent;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import support.Library;

/**
 *
 * @author Bhaumik
 */
public class ChangePassword extends javax.swing.JInternalFrame {

    /**
     * Creates new form ChangePassword
     */
    Library lb = new Library();
    Connection dataConnection = HMS101.connMpAdmin;

    public ChangePassword() {
        initComponents();
        registerShortKeys();
    }

    public static String getMD5(String data) throws NoSuchAlgorithmException {
        MessageDigest messageDigest = MessageDigest.getInstance("MD5");

        messageDigest.update(data.getBytes());
        byte[] digest = messageDigest.digest();
        StringBuffer sb = new StringBuffer();
        for (byte b : digest) {
            sb.append(Integer.toHexString((int) (b & 0xff)));
        }
        return sb.toString().replaceAll("0", "00");
    }

    @Override
    public void dispose() {
        try {
            HMSHome.removeFromScreen(HMSHome.tabbedPane.getSelectedIndex());
            super.dispose();
        } catch (Exception ex) {
            lb.printToLogFile("Exception at dispose at codeBinding", ex);
        }
    }

    private void registerShortKeys() {
        lb.setShortcut(this, jbtnClose);
    }

    private void jbtnChangePwdActionPerformedRoutine() {
        if (jtxtNewPwd.getText().trim().equalsIgnoreCase(jtxtConfirmPwd.getText().trim())) {
            try {
                String sql = "update login set password = md5(?) where user_id=?";
                PreparedStatement pstLocal = dataConnection.prepareStatement(sql);
                pstLocal.setString(1, jtxtNewPwd.getText());
                pstLocal.setInt(2, HMSHome.user_id);
                int result = pstLocal.executeUpdate();
                if (result == 1) {
                    JOptionPane.showMessageDialog(this, "Password Change Sucessfully", "Change Password", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Password Change is unSucessfull", "Change Password", JOptionPane.ERROR_MESSAGE);
                    jtxtNewPwd.requestFocusInWindow();
                }
            } catch (Exception ex) {
                lb.printToLogFile("Exception at jbtnChangePwdActionPerformedRoutine", ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "New password and confirm password are not match.", "Change Password", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtConfirmPwd = new javax.swing.JPasswordField();
        jtxtNewPwd = new javax.swing.JPasswordField();
        jbtnChangePwd = new javax.swing.JButton();
        jbtnClose = new javax.swing.JButton();

        jLabel2.setText("New Password");

        jLabel3.setText("Confirm Password");

        jtxtConfirmPwd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtConfirmPwdKeyPressed(evt);
            }
        });

        jtxtNewPwd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtNewPwdKeyPressed(evt);
            }
        });

        jbtnChangePwd.setText("Change");
        jbtnChangePwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnChangePwdActionPerformed(evt);
            }
        });
        jbtnChangePwd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnChangePwdKeyPressed(evt);
            }
        });

        jbtnClose.setText("Cancel");
        jbtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtConfirmPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtNewPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(jbtnClose))
                            .addComponent(jbtnChangePwd))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jtxtNewPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jtxtConfirmPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnChangePwd)
                    .addComponent(jbtnClose))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, jtxtNewPwd});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel3, jtxtConfirmPwd});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtConfirmPwdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtConfirmPwdKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jbtnChangePwd.requestFocusInWindow();
        }
    }//GEN-LAST:event_jtxtConfirmPwdKeyPressed

    private void jtxtNewPwdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtNewPwdKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtxtConfirmPwd.requestFocusInWindow();
        }
    }//GEN-LAST:event_jtxtNewPwdKeyPressed

    private void jbtnChangePwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnChangePwdActionPerformed
        // TODO add your handling code here:
        jbtnChangePwdActionPerformedRoutine();
    }//GEN-LAST:event_jbtnChangePwdActionPerformed

    private void jbtnChangePwdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnChangePwdKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jbtnChangePwdActionPerformedRoutine();
        }
    }//GEN-LAST:event_jbtnChangePwdKeyPressed

    private void jbtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbtnCloseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbtnChangePwd;
    private javax.swing.JButton jbtnClose;
    private javax.swing.JPasswordField jtxtConfirmPwd;
    private javax.swing.JPasswordField jtxtNewPwd;
    // End of variables declaration//GEN-END:variables
}
